---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: argus-eye
  name: argus-eye
  namespace: argus
spec:
  tags:
  - name: v0.1.0
    from:
      kind: DockerImage
      name: clustergarage/argus-eye:v0.1.0
  - name: latest
    from:
      kind: DockerImage
      name: clustergarage/argus-eye:latest
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: argus-eye
  namespace: argus
  labels:
    app: argus-eye
spec:
  replicas: 1
  selector:
    app: argus-eye
  template:
    metadata:
      labels:
        app: argus-eye
    spec:
      containers:
      - name: argus-eye
        image: clustergarage/argus-eye:v0.1.0
        ports:
        - name: node
          containerPort: 3000
        securityContext:
          runAsUser: 0
      serviceAccountName: argus-admin
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - argus-eye
      from:
        kind: ImageStreamTag
        name: argus-eye:v0.1.0
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: argus-eye
  namespace: argus
  labels:
    app: argus-eye
spec:
  selector:
    app: argus-eye
  clusterIP: None
  ports:
  - name: node
    protocol: TCP
    port: 3000
    targetPort: node
